export const GET_TOURNAMENT_DATA = "GET_TOURNAMENT_DATA";
export const TOURNAMENT_DATA_SUCCESS = "TOURNAMENT_DATA_SUCCESS";
export const GET_GOLFER_GROUPINGS = "GET_GOLFER_GROUPINGS";
export const GOLFER_GROUPINGS_SUCCESS = "GOLFER_GROUPINGS_SUCCESS";
